name: Build for Android

on:
  workflow_call:
    inputs:
      mihomo_version:
        description: Mihomo version.
        required: true
        type: string
      dashboard_version:
        description: Dashboard version.
        required: true
        type: string
      tag:
        description: Tag name.
        required: true
        type: string
      mihomo_asset_keyword:
        description: Keyword to match mihomo android asset.
        required: false
        default: mihomo-android-arm64-v8-v*.gz
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    env:
      MIHOMO_REPO: MetaCubeX/mihomo
      DASHBOARD_REPO: Zephyruso/zashboard

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.tag }}

      - name: Prepare staging directory
        run: |
          mkdir -p staging-android/bin/xclash
          mkdir -p staging-android/clash
          mkdir -p staging-android/ui

          find . -maxdepth 1 -type f \( -name "*.yaml" \) -exec cp {} staging-android/clash/ \;
          cp etc/package.list.cfg staging-android/

      - name: Download and extract Zashboard
        run: |
          curl -L https://github.com/${{ env.DASHBOARD_REPO }}/archive/refs/heads/gh-pages-no-fonts.zip -o ui.zip
          unzip -q ui.zip -d ui_temp/

          mv ui_temp/*/* staging-android/ui/
          rm -rf ui_temp/ ui.zip

      - name: Download and process Mihomo
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release download ${{ inputs.mihomo_version }} \
            -R ${{ env.MIHOMO_REPO }} \
            -p "${{ inputs.mihomo_asset_keyword }}" \

          GZ_FILE=$(ls *.gz | head -n 1)

          gunzip -q "$GZ_FILE"

          cd staging-android

          BIN_FILE=$(ls ../mihomo-android-* | head -n 1)

          if [ -n "$BIN_FILE" ]; then
            mv "$BIN_FILE" bin/xclash/mihomo
          else
            echo "Error: Mihomo bin file not found!"
            exit 1
          fi

          cd ..
          rm "$GZ_FILE"

      - name: Create zip package
        id: package
        run: |
          M_VER=$(echo "${{ inputs.mihomo_version }}" | sed 's/^v//')
          D_VER=$(echo "${{ inputs.dashboard_version }}" | sed 's/^v//')
          FINAL_NAME="android-m${M_VER}-z${D_VER}.zip"

          cd staging-android
          zip -r "../$FINAL_NAME" .
          echo "file_name=$FINAL_NAME" >> "$GITHUB_OUTPUT"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-package
          path: ${{ steps.package.outputs.file_name }}
